Task:
  project: 'template' # Model Int Name
  runID:   'demo'     # run ID
  mode:    'test'    # [train, test]
  logger:  'local'    # ['local', 'wandb', ...]
  seed:     2024

Trainer:
  train_logger_name: 'train'
  valid_logger_name: 'valid'
  max_epoch: 30
  batch_size: 32
  # enable if (early_stop < max_epoch)
  early_stop: 100   
  
Tester:
  test_logger_name: 'test'
  model_path: ''
  batch_size: 32

BenchMark:
  - ConfuseMatrix

# Model Integration Configs  
ModelInt:
  name: 'template'
  dataset: 'template_dataset'
  # model args config
  model_args: {}
  # optimizer args config
  optim_args: 
    lr: 1e-4
    # weight_decay: 1e-3

Logger:
  track_list:
    - 'train/epoch'
    - 'train/loss'
    - 'valid/epoch'
    - 'valid/loss'
    - 'valid/ConfuseMatrix:*'
    - 'test/ConfuseMatrix:*'

